### ISSUE TITLE
Fix - Middleware crashes without logger

### ISSUE THREAD

**Issue by eiabea** [rimiti/redis-keyman#16]
First of all: many thanks for continuing this project!

i switched from node-acl to aclify and initialized it without a dedicated logger:

`
const acl = new Acl(new MemoryStore());
`

when i try to utilize the middleware i get:

`
TypeError: instance.logger.debug is not a function
`

i looked into [acl.js](https://github.com/Aclify/aclify/blob/6c85484be25ceb705962174ca4c5904b786003eb/src/classes/acl.js#L19) and the default logger function is an empty object which explains the issue

**Comment by rimiti** [comment]
Hi @eiabea,

Thank your for your interest. 👍 
I confirm you this is a dirty bug, I'll fix it this week.

Dimitri,

**Comment by rimiti** [comment]
Hi @eiabea,

Thank you for your propose, your code has been merged.

Have a nice day.
Dimitri,
