### ISSUE TITLE
Variables in resource not working

### ISSUE THREAD

**Issue by eiabea** [rimiti/redis-keyman#28]
I think i already had this issue in the original acl package, or i misunderstood this feature

```
await acl.allow([
  {
    roles: ['testGroup'],
    allows: [
      { resources: '/v1/users', permissions: ['post', 'get'] },
      { resources: '/v1/users/:id', permissions: ['get', 'delete'] },
    ],
  },
]);

await acl.addUserRoles('admin-1337', 'testGroup');

console.log(await acl.isAllowed('admin-1337', '/v1/users', 'get')); // returns true
console.log(await acl.isAllowed('admin-1337', '/v1/users/1234', 'get')); // returns false
```

shouldn't the second permission check also return true?

**Comment by rimiti** [comment]
Hello @eiabea,

The `:id` isn't dynamic, you should develop your own strategy.
For example, if you use express, you can use this middleware strategy:

```
/**
 * @description Check if user has rights on url
 * @param req
 * @param res
 * @param next
 */
export default function (req, res, next) {
  const userId = req.feathers.user ? req.feathers.user.id : 'anonymous';
  Acl.isAllowed(userId, req.swagger.apiPath, req.method.toLowerCase(), (err, result) => {
    if (result) return next();
    console.log(`[acl/mid] - userId: ${userId}, path: ${req.swagger.apiPath}, method: ${req.method.toLowerCase()}`);
    return next(new errors.Forbidden('NOT_AUTHORIZED'));
  });
}
```

You have to compare paths, no urls. ;)

Dimitri,

**Comment by eiabea** [comment]
Thank you for the feedback. I looked into this and thought about enabling regex support for the resources to cover this as a feature, like:

```
{ resources: /\/v1\/users\/[1-9]+/i, permissions: ['get', 'delete'] }
```

An URL like _/v1/users/5_ would then be allow to get and delete this resource

**Comment by rimiti** [comment]
Regex support could be a nice feature but you have to be careful in the implementation to don't make breaking changes. :)

**Comment by eiabea** [comment]
Your recommendation does not really fit what i try to do, maybe the following example helps to explain:

1. Creating admin user
2. Creating ACL for admin role
```
{
  roles: ['admin-role'],
  allows: [
    { resources: '/v1/users', permissions: ['post', 'get'] },
    { resources: '/v1/users/:guid', permissions: ['get', 'update', 'delete'] },
  ],
}
```
3. Adding admin user to admin-role
```
await acl.addUserRoles('admin', 'admin-role');
```
4. Creating ordinary user
5. Creating ACL for user role
```
{
  roles: ['user-role'],
  allows: [
    { resources: '/v1/users/39da4520-475f-4eb0-9a6b-c61a7bf460a4', permissions: ['get', 'update', 'delete'] },
  ],
}
```
6. Adding user to user-role
```
await acl.addUserRoles('user', 'user-role');
```
7. Creating /v1/users route
```
const authorize = numPathComponents =>
  acl.middleware(numPathComponents || 0, req => req.user.guid);

router.post(
  '/',
  passport.authenticate('jwt', { session: false }),
  authorize(),
  async (req, res) => {
    // TODO create user
    // TODO send response
  },
);

router.get(
  '/:guid',
  passport.authenticate('jwt', { session: false });
  authorize(),
  async (req, res) => {
    const { guid } = req.params;

    // TODO get user
    // TODO send response
  },
);

router.update(
  '/:guid',
  passport.authenticate('jwt', { session: false });
  authorize(),
  async (req, res) => {
    const { guid } = req.params;

    // TODO update user
    // TODO send response
  },
);

router.delete(
  '/:guid',
  passport.authenticate('jwt', { session: false });
  authorize(),
  async (req, res) => {
    const { guid } = req.params;

    // TODO delete user
    // TODO send response
  },
);
```

What i would expect, because the admin role is allowed to delete any user

1. Login as admin
2. Getting admin token
3. Sending request to delete an ordinary user
```
const response = await chai.request(app)
  .delete('/v1/users/39da4520-475f-4eb0-9a6b-c61a7bf460a4')
  .set('Authorization', `JWT ${adminToken}`);
const { body } = response;
assert.isTrue(body.success);
```

What i would expect, because the user role is allowed to delete its own user

1. Login as user
2. Getting user token
3. Sending request to delete own user
```
const response = await chai.request(app)
  .delete('/v1/users/39da4520-475f-4eb0-9a6b-c61a7bf460a4')
  .set('Authorization', `JWT ${userToken}`);
const { body } = response;
assert.isTrue(body.success);
```

What i would expect, because the user role is NOT allowed to delete any other user

1. Login as user
2. Getting user token
3. Sending request to delete own user
```
const response = await chai.request(app)
  .delete('/v1/users/dbd26044-fd91-418e-8dbf-a122e4a08a7a')
  .set('Authorization', `JWT ${userToken}`);
const { body } = response;
assert.isFalse(body.success); // or status code 403
```

Do i expect the wrong functionality of this package or is this just a missing feature?

If it is a missing feature, would a regex support be the solution?

**Comment by rimiti** [comment]
Sorry for my last answer and the lack of precision.

In your case, you're trying use a dynamic resources but Aclify doesn't understand url parameters.
It only compare resources as string.

You have two solutions:

1- Store each paths ('/v1/users/dbd26044-fd91-418e-8dbf-a122e4a08a7a') and associate them  to your user. It's not the best way... Your ACL rights will be very complicated for nothing...

2- Else, you create generic access like:

```
{
  roles: ['admin-role', 'user-role'],
  allows: [
    { resources: '/v1/users', permissions: ['post', 'get'] },
    { resources: '/v1/users/:guid', permissions: ['get', 'update', 'delete'] },
  ],
}
await acl.addUserRoles('admin', 'admin-role');
await acl.addUserRoles('user', 'user-role');
```

And you create ACL model function to verify if the `user` can access on the `dbd26044-fd91-418e-8dbf-a122e4a08a7a` resource. 

Where are stored you guid ? If it's in a database, you should have 
- ACL Service : Verify paths access without params check => Aclify
- ACL Model : Your custom functions when when the user has pass the ACL Service step, you check if it has rights on `dbd26044-fd91-418e-8dbf-a122e4a08a7a` resource.

It's more clear now ? This strategy depends of each projects.

I'll write ASAP an article with some examples.
