### ISSUE TITLE
Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by Nadeem1337** [rimiti/redis-keyman#40]
Hi, i am facing the following issue.
Unhandled rejection TypeError: Cannot read property 'reduce' of undefined
    at MySQL.end (E:\xampp\htdocs\echallan\node_modules\@aclify\aclify\dist\src\stores\sequelize.js:48:28)

**Comment by rimiti** [comment]
Thank you @Nadeem1337 for you this issue.

I'm working hard on a hard refactoring of this package.
You can check changes into this branch: https://github.com/Aclify/aclify/tree/hard-refactoring

**Comment by ekeuus** [comment]
@rimiti Could you explain shortly what you mean by hard refactoring?

**Comment by Nadeem1337** [comment]
@rimiti what i should do now ?

**Comment by rimiti** [comment]
@ekeuus Aclify will be totally rewrited with typescript. It must be strictly typed to be improved with new features and adapters.
@Nadeem1337 Waiting or creating a pull request :)
